# Generated by Django 3.2.15 on 2022-10-01 19:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('url', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beats', models.CharField(max_length=32)),
                ('beat_volumes', models.CharField(max_length=32)),
                ('track_volume', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)])),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track', to='beats_app.instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Drumloop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='brand_new_loop', max_length=50, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('allow_copy', models.BooleanField(default=True)),
                ('tempo', models.IntegerField(default=120, validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(60)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drum_loop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
