# Generated by Django 3.2.15 on 2022-10-02 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='instrument',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beats_app.instrument'),
        ),
    ]
