# Generated by Django 3.2.15 on 2022-10-22 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drumloop',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
