# Generated by Django 3.2.15 on 2022-10-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drumloop',
            name='user',
        ),
    ]
