# Generated by Django 3.2.15 on 2022-10-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0002_remove_drumloop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='drumloop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='beats_app.drumloop'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='track',
            name='instrument',
        ),
        migrations.AddField(
            model_name='track',
            name='instrument',
            field=models.ManyToManyField(to='beats_app.Instrument'),
        ),
    ]
