# Generated by Django 3.2.15 on 2022-11-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0002_drumloop_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drumloop',
            name='allow_copy',
        ),
        migrations.RemoveField(
            model_name='track',
            name='beat_volumes',
        ),
        migrations.AlterField(
            model_name='track',
            name='beats',
            field=models.CharField(default='00000000000000000000000000000000', max_length=32),
        ),
    ]
