# Generated by Django 3.2.15 on 2022-10-19 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats_app', '0002_alter_track_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='drumloop',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='drumloops', to=settings.AUTH_USER_MODEL),
        ),
    ]
