# Generated by Django 3.2.15 on 2022-11-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0005_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=100),
        ),
    ]
