# Generated by Django 3.2.15 on 2022-11-09 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('beats_app', '0006_auto_20221106_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drumloop',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drumloops', to=settings.AUTH_USER_MODEL),
        ),
    ]
