# Generated by Django 3.2.15 on 2022-11-20 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0007_alter_drumloop_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drumloop',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
