# Generated by Django 3.2.15 on 2022-12-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0008_alter_drumloop_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drumloop',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
