# Generated by Django 3.2.15 on 2022-12-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beats_app', '0009_alter_drumloop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drumloop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
